### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by yuliaa00** [StEugen/small-trafficbot#1]
Hii,

can you please help me out??

**Comment by StEugen** [comment]
Sure, what's the problem?

**Comment by StEugen** [comment]
> Hii,
> 
> can you please help me out??

Sure, what's the problem?

**Comment by yuliaa00** [comment]
Do you perhaps have Telegram or Discord?

**Comment by StEugen** [comment]
Sorry, if you have any questions or need help about this project, ask here, please

**Comment by yuliaa00** [comment]
ok
